version: '3.8'

services:
  mysql:
    image: mysql/mysql-server
    container_name: seu-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
